# apiVersion: "serving.kserve.io/v1beta1"
# kind: "InferenceService"
# metadata:
#   name: "style-sample"
# spec:
#   predictor:
#     # model:
#     #   modelFormat:
#     onnx:
#       storageUri: "gs://kfserving-examples/models/onnx"
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "style-sample"
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storageUri: "gs://kfserving-examples/models/onnx"
