# REF: https://github.com/golangci/golangci-lint-action

name: GO Lint Check

on:
  push:
    branches: [master, release*]
  pull_request:
    branches: []
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
          version: v1.55.2
          args: --go=1.21
